apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-game-store
spec:
  replicas: 5
  selector:
    matchLabels:
      app: video-game-store
  template:
    metadata:
      labels:
        app: video-game-store
    spec:
      containers:
        - name: video-game-store
          image: vasilxb/video_game_store:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/video_game_db
