apiVersion: v1
kind: Service
metadata:
  name: video-game-store-service
spec:
  type: NodePort
  selector:
    app: video-game-store
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
